---
title: "PycnoPie"
format: 
  html:
    code-fold: true
    page-layout: full
editor: visual
date: last-modified
---

*An analysis of the percentage change in kelp consumed across urchin source habitats (urchin barren or kelp forest) and predator treatments (seastar present/ no seastar present)*

```{r}
#| echo: false

knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
#| message: false
#| echo: false

#loading libraries
library(tidyverse)
library(here)
library(googlesheets4)
```

```{r}
#| message: false

#pulling data from web ---------------------------------------------------------
kelp <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1yFkZm64m7c9b4EdSxK3-qR8B7I-5rWyk7CDs7fmmMKg/edit?gid=184409314#gid=184409314",
                          "Kelp") 
```

```{r}
#| message: false
#| echo: false

#cleaning/manipulation
#creating new column for pred/urch treatment
#calculating % change kelp grazed
kelp_processed <- kelp %>%
  separate(Treatment, "_(?=[^_]*$)",
           into = c("Pred_treatment", "Urch_habitat_treatment"), 
           remove = FALSE) %>%
  mutate(pcnt_grazed = ((Kelp_weight_before_g - Kelp_weight_after_g)/ 
                          Kelp_weight_before_g)*100)
```

### Trials included in following graphs:

```{r}
#| message: false

#overview of kelp data
unique(subset(kelp_processed, !is.na(pcnt_grazed))$Trial)
```

### Urchin source habitat vs. kelp grazed for different predator treatments

```{r}

#graph 
ggplot(data = subset(kelp_processed, !is.na(pcnt_grazed)), aes(x = Urch_habitat_treatment, y = pcnt_grazed, 
                                  fill = Pred_treatment) ) +
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = c('#5A5A5A','#DAF7A6') ) +
  ylab("% Change Kelp Grazed") +
  labs(fill = "Pred treatment")

```
