---
title: "PycnoPie"
format: 
  html:
    code-fold: true
    page-layout: full
editor: visual
date: last-modified
---

*Select results and interpretation from PycnoPie experiment run in the summer of 2024 on indirect effects of Pycnopodia helianthoides on grazing rates of red urchins from kelp forests and urchin barrens.*

```{r}
#| echo: false

knitr::opts_chunk$set(warning = FALSE, message = FALSE)
```

```{r}
#| message: false
#| echo: false

#loading libraries
library(tidyverse)
library(here)
library(googlesheets4)
library(strex)
library(lme4)
library(performance)
library(sjPlot)
```

```{r}
#| message: false
#| echo: false

source(here::here("./scripts/00_cleaning.R"))
source(here::here("./scripts/01_manipulation.R"))

```

## Analysis of kelp grazed by urchins

Boxplot of raw data for percentage of kelp grazed by urchin habitat treatment and predator treatment

```{r}
#kelp grazed by predator/urchin treatment
ggplot(data = subset(kelp_processed, !is.na(pcnt_grazed)), aes(x = Urch_habitat_treatment, y = pcnt_grazed, 
                                                               fill = Pred_treatment) ) +
  geom_boxplot() +
  theme_classic() +
  scale_fill_manual(values = c('#5A5A5A','#DAF7A6') ) +
  ylab("% Change Kelp Grazed") +
  labs(fill = "Pred treatment")

```
